# Generated by Django 5.2.7 on 2025-10-08 10:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('mobileNo', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valied Number', regex='^\\d{10,15}$')])),
                ('signup_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='d65e587c24e803af7223381869043a978e7edf09fc02e70747afcef43f37dc96', max_length=64, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.signupmodel')),
            ],
        ),
    ]
