# Generated by Django 5.2.7 on 2025-10-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='e9320395062e11cc4a99288ab156614442058ad8f603e5af12f8528ae13caacf', max_length=64, unique=True),
        ),
    ]
