# Generated by Django 5.2.7 on 2025-10-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='24685c579704b1a0150d6acb039c48ef599799ddc4bf541fbe53f79164700c07', max_length=64, unique=True),
        ),
    ]
