# Generated by Django 5.2.7 on 2025-10-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='d6da5be2a150866d94a3dd804e2191815b6e9180595172dcd2cc08c747d40767', max_length=64, unique=True),
        ),
    ]
