# Generated by Django 5.2.7 on 2025-10-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_signupmodel_groups_signupmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='f00f87fad1a38e0fc517f001af8721a4030f4d41f630d6bab6c40983a6319233', max_length=64, unique=True),
        ),
    ]
