# Generated by Django 5.2.7 on 2025-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_signupmodel_password_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='5925389236fe89ce12a44a0c17bc783b42e18a4f38bf005bd852ac672cabd9da', max_length=64, unique=True),
        ),
    ]
