# Generated by Django 5.2.7 on 2025-10-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='6cb83114eb4419e9c2473b1a52ad4aa3f933a12045fcb1878d3af6a733bce42c', max_length=64, unique=True),
        ),
    ]
