# Generated by Django 5.2.7 on 2025-10-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='845f6ce3473c6ce22e540e80e9264140c98e7816f8444d9e233ebbe7d31b48e8', max_length=64, unique=True),
        ),
    ]
