# Generated by Django 5.2.7 on 2025-10-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='a3243ac082fb4419fe71b2070a2e376b4d4e5e80f385880ba329759484d1b098', max_length=64, unique=True),
        ),
    ]
