# Generated by Django 5.2.7 on 2025-10-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_byeragentvisiterlocationdetails_propertyfeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='9b5aaf768d1a4f2cf13e58906679eeb6435b9312d6fbd2dd93854661757d1e00', max_length=64, unique=True),
        ),
    ]
