# Generated by Django 5.2.7 on 2025-10-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='828e6642383fb42b914f3d292e2d2692ea2f0d911d4cb1a696ab8c75ff31c07c', max_length=64, unique=True),
        ),
    ]
