# Generated by Django 5.2.7 on 2025-10-17 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_usertoken_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydetails',
            old_name='name',
            new_name='businessname',
        ),
        migrations.RenameField(
            model_name='propertydetails',
            old_name='propertydescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='propertytype',
            old_name='name',
            new_name='property_typename',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfavorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='image_count', to='property.propertyimage'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='listed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_ownername', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_location', to='property.byeragentvisiterlocationdetails'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='propertytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_type', to='property.propertytype'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_name', to='property.propertystatus'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='a68aba944132099a5f589eafc3f2775887327cbe76f77a8b951174dd41d29ae2', max_length=64, unique=True),
        ),
    ]
