# Generated by Django 5.2.7 on 2025-10-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_rename_name_propertydetails_businessname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='3b7d43f66c093108320fa573a293bddc3e3ed3b11a3d75227aee5106c056e970', max_length=64, unique=True),
        ),
    ]
