# Generated by Django 5.2.7 on 2025-10-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_usertoken_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystatus',
            name='property_statusname',
            field=models.CharField(default='Rented', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='1b8283d927e01209b12eb11d2deefa2fccc103a2e8260196d16834c044cf8d5c', max_length=64, unique=True),
        ),
    ]
