# Generated by Django 5.2.7 on 2025-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_propertystatus_property_statusname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='c273e86de832682cb41b22000d97a0d5c35d0249228bdc183784c04dcd2c0854', max_length=64, unique=True),
        ),
    ]
