# Generated by Django 5.2.7 on 2025-11-07 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_alter_usertoken_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='cts',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-22 18:38:18.251368+05:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='uts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='byeragentvisiterlocationdetails',
            name='cts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='byeragentvisiterlocationdetails',
            name='uts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='uts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='cts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='uts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertyfeature',
            name='cts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyfeature',
            name='uts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertyfeaturevalue',
            name='cts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyfeaturevalue',
            name='uts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertyinquery',
            name='uts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertystatus',
            name='cts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertystatus',
            name='uts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='cts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertytype',
            name='uts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='uts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='e50f4c40dfbb28a4db0f0622cbefac6d0dddaf21a3d36a850ee0ab726fc75c48', max_length=64, unique=True),
        ),
    ]
