# Generated by Django 5.2.7 on 2025-11-07 10:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_agentprofile_cts_agentprofile_uts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))]),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='5ecd17571985f18d499295b33ae43af113718a8e741ea455ffd87cb09863706c', max_length=64, unique=True),
        ),
    ]
