# Generated by Django 5.2.7 on 2025-11-20 11:37

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_review_rating_alter_usertoken_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='contactnumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, validators=[django.core.validators.RegexValidator(regex='\\d{10,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='d29743de2bf42c4b0c73abf38e69b907e962eb726dbc5462b84d0df36d44bc59', max_length=64, unique=True),
        ),
    ]
