# Generated by Django 5.2.7 on 2025-11-20 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_agentprofile_contactnumber_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='contactnumber',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='ece0472c3c2c4b9650ba6ac61c050a47c2b6b04dcef019aeeed64f8e4804258a', max_length=64, unique=True),
        ),
    ]
