# Generated by Django 5.2.7 on 2025-11-20 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_alter_agentprofile_contactnumber_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='contactnumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='974a75c2352185c94cede0c4cb78595532676c2abba1ed8973b8c7ae330b51eb', max_length=64, unique=True),
        ),
    ]
