# Generated by Django 5.2.7 on 2025-11-20 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_alter_agentprofile_contactnumber_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='contactnumber',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='7660b4944af77bf0efaa25b31dc26ce10ed1ace3cd6672516e6afafdef7801a2', max_length=64, unique=True),
        ),
    ]
