# Generated by Django 5.2.7 on 2025-11-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_alter_agentprofile_contactnumber_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='bd4c33d7771259a2c06ecd8eb1a9ba08b1f96c02678e176649b71ad427f9f5ae', max_length=64, unique=True),
        ),
    ]
