# Generated by Django 5.2.7 on 2025-11-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='365818d014d932078d6d4befd2620ee4c9f6d607f16be10f2cd116ee4ca26b0b', max_length=64, unique=True),
        ),
    ]
