# Generated by Django 5.2.7 on 2025-11-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='2ea92515302ff366728636a7b5a66c3a40d4573987ec4f3d9857e5341b3dffe0', max_length=64, unique=True),
        ),
    ]
