# Generated by Django 5.2.7 on 2025-11-20 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='contactnumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='41bfdf2b763dbc30d2479bae817fa58a77137a0bb89c012ab20b20998347cd23', max_length=64, unique=True),
        ),
    ]
