# Generated by Django 5.2.7 on 2025-11-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('property', '0027_alter_agentprofile_contactnumber_alter_usertoken_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='56751b2dc2cf90f1cab6081040f12121b235a829d5a97f550bc689c475713ad4', max_length=64, unique=True),
        ),
    ]
