# Generated by Django 5.2.7 on 2025-11-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_signupmodel_groups_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='1b8a81afda35f795699f706ade2460097152fea99860ba6cde1823474cb1f07a', max_length=64, unique=True),
        ),
    ]
