# Generated by Django 5.2.7 on 2025-11-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0029_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default='6b8aa0756868ff69a3e5cb6f6f0c6aaa1c3dbf722d1d8f4a58b82396f42fe2ea', max_length=64, unique=True),
        ),
    ]
