# Generated by Django 5.2.7 on 2025-12-19 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_alter_usertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
