# Generated by Django 5.2.7 on 2025-12-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0031_alter_usertoken_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNo', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('isused', models.BooleanField(default=False)),
                ('cts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
