# Generated by Django 5.2.7 on 2025-12-20 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0032_otpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='exp_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
