# Generated by Django 5.2.7 on 2026-01-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0034_captchamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='image_count', to='property.propertyimage'),
        ),
    ]
