# Generated by Django 5.2.7 on 2026-01-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0035_alter_propertydetails_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='propertyimage', to='property.propertyimage'),
        ),
    ]
