# Generated by Django 5.2.7 on 2026-01-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0036_alter_propertydetails_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='properties_image/'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='totalsell',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
