# Generated by Django 5.2.7 on 2026-01-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0037_agentprofile_profileimage_agentprofile_totalsell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='agencyname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
