# Generated by Django 6.0.1 on 2026-01-24 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0038_alter_agentprofile_agencyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{10,15}$')]),
        ),
    ]
