# Generated by Django 6.0.1 on 2026-03-13 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0039_remove_agentprofile_email_agentprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(default='rahul123@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(default='Rahul kumar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(default='8520109012', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Number', regex='^\\d(10, 15)$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyinquery',
            name='email',
            field=models.EmailField(default='rahul123@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyinquery',
            name='name',
            field=models.CharField(default='Rahul kumar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyinquery',
            name='phone',
            field=models.CharField(default='8520109012', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Number', regex='^\\d(10, 15)$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyinquery',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
