# Generated by Django 6.0.1 on 2026-03-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0040_contactrequest_email_contactrequest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='uts',
        ),
        migrations.RemoveField(
            model_name='propertyinquery',
            name='uts',
        ),
    ]
