# Generated by Django 6.0.1 on 2026-03-13 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0042_alter_contactrequest_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Number', regex='^\\d{10,20}$')]),
        ),
        migrations.AlterField(
            model_name='propertyinquery',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Number', regex='^\\d{10,20}$')]),
        ),
    ]
