# Generated by Django 6.0.1 on 2026-05-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0044_alter_contactrequest_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="byeragentvisiterlocationdetails",
            name="latitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="byeragentvisiterlocationdetails",
            name="longitude",
            field=models.FloatField(default=(0)),
            preserve_default=False,
        ),
    ]
