# Generated by Django 6.0.1 on 2026-05-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0045_byeragentvisiterlocationdetails_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="byeragentvisiterlocationdetails",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="byeragentvisiterlocationdetails",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
