# Generated by Django 6.0.1 on 2026-06-22 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0047_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{10,15}$')]),
        ),
    ]
